### ISSUE TITLE
Does anyone actually use the  SetCharacters method?

### ISSUE THREAD

**Issue by bolorundurowb** [bolorundurowb/shortid#18]
If it is not in use, then we can consider removing it in the next major release

**Comment by svenbit** [comment]
I used SetCharacters in one of the project to generate uppercased+number only shortid

```C#
string shortIdCharacters = "ABCDEFGHIJKLMNOPQRSTUVWXQYZ1234567890";

ShortId.SetCharacters(shortIdCharacters);

var opts = new GenerationOptions
{
   UseSpecialCharacters = false,
   UseNumbers = true,
   Length = 12
};

ShortId.Generate(opts);
```

**Comment by inexuscore** [comment]
@svenbit This doesn't work, the library throws an **InvalidOperationException** saying **The replacement characters must be at least 50 letters in length and without whitespace**. I'd like to generate uppercase letters only + digits. Any ideas?

**Comment by bolorundurowb** [comment]
@inexuscore the limitation was added in version 3.0.0 to improve uniqueness of generated ids. If you want to limit the character set then you can use [version 2.0.4](https://www.nuget.org/packages/shortid/2.0.4)

**Comment by inexuscore** [comment]
@bolorundurowb ah I see, that's what I thought. Thank you very much, I'll stick with the latest version. Better to have more uniqueness than unreliable IDs.

**Comment by djordjedjukic** [comment]
@inexuscore I am using something like this:

`ShortId.Generate(true, false, 12).Insert(6, "-").ToUpper()`

Only numbers. length 12 and dash in the middle.

**Comment by inexuscore** [comment]
@djordjedjukic brilliant, thank you.
