### ISSUE TITLE
URL safe

### ISSUE THREAD

**Issue by burhanfarooqoffice** [bolorundurowb/shortid#25]
Hi,

Please can you confirm if the shortid is url safe?
Or need to make them URL safe?

Please advice & suggest.

Thanks

**Comment by bolorundurowb** [comment]
@burhanfarooqoffice yes, the short ids generated are URL safe, but you can be doubly sure by url encodding them

```csharp
var urlSafeId = HttpUtility.UrlEncode(generatedId);
```
