### ISSUE TITLE
Are you trying to port dylang's shortid to C#?  Problems with approach...

### ISSUE THREAD

**Issue by dougrday** [bolorundurowb/shortid#3]
I'm toying with the idea of creating my own port, and I saw your library and thought "maybe I won't need to".  Unfortunately, I don't think I can use this as-is -- there are a few issues with your approach compared to node's "shortid" library:

1.  It's stateless.  Node's version keeps track of how many times you've asked for a unique ID in a very short period of time.  This stateful behavior helps ensure the uniqueness of IDs.
2.  Length is random between 7-14.  Node's version only increases the length of the unique ID if you need to, to guarantee uniqueness.  The more times you ask for an ID within the same second, the longer the ID becomes.
3.  No support for clusters.  Node's version allows up to 16 machines in a cluster to generate unique IDs without the possibility of collisions.

Thoughts?

**Comment by bolorundurowb** [comment]
@dougrday yes, my aim was and is to create a port of dylang's library. You have raised several valid points and a few others have been raised on reddit which I am looking to address in a future release

**Comment by dougrday** [comment]
@bolorundurowb Great, thanks.

**Comment by bolorundurowb** [comment]
@dougrday  I have been going through a dylang's implementation and I have a few rebuttals regarding your points above.

> It's stateless. Node's version keeps track of how many times you've asked for a unique ID in a very short period of time. This stateful behaviour helps ensure the uniqueness of IDs.

The reason he needs to keep track of how quickly you are requesting an id is that he is requesting an instance of the rng for every call and since the rng is based on the clock, he needs to ensure his rng doesn't have the same state. I am using a single `Random` instance so no matter how many requests are being made per millisecond, the instance would generate differently.

> Length is random between 7-14. Node's version only increases the length of the unique ID if you need to, to guarantee uniqueness. The more times you ask for an ID within the same second, the longer the ID becomes.

Part of the aim of this "port" was to give the user the ability to control the length of the id. With v2.0.0 a lower limit of 7. Since we dont have the restrictions on the rng as NodeJS does, we dont need a longer id to endure uniqueness.

> No support for clusters. Node's version allows up to 16 machines in a cluster to generate unique IDs without the possibility of collisions.

v2.0.0 adds support for threading, I am not sure of what you mean by clusters though. do you mean instances of the application?

**Comment by dougrday** [comment]
@bolorundurowb 

> The reason he needs to keep track of how quickly you are requesting an id is that he is requesting an instance of the rng for every call and since the rng is based on the clock, he needs to ensure his rng doesn't have the same state. I am using a single Random instance so no matter how many requests are being made per millisecond, the instance would generate differently.

I'm not sure you've looked through the source of shortid; the same rng source is used each time, and it doesn't use clock-based random numbers -- it uses this:  https://developer.mozilla.org/en-US/docs/Web/API/RandomSource/getRandomValues

Keep doing research on preventing collisions, and you'll find that a timestamp as part of the UI is (nearly) always a part of the equation.  With a library like shortid, the chance of collision is function of the amount of load on a server at a given time.  Without a timestamp portion of ID, this is more difficult to achieve.

> Part of the aim of this "port" was to give the user the ability to control the length of the id. With v2.0.0 a lower limit of 7. Since we dont have the restrictions on the rng as NodeJS does, we dont need a longer id to endure uniqueness.

I disagree that a library named `shortid` should aim to let the user control the size of the library; rather, it should attempt to provide the shortest id that can guarantee uniqueness.  A timestamp as part of the ID ends up being critical in this equation to keep the size small.

> v2.0.0 adds support for threading, I am not sure of what you mean by clusters though. do you mean instances of the application?

If you're generating thousands or tens of thousands of ids per second, and as your application scales, you need to add special cluster support (e.g. multiple machines all generating IDs) to ensure you don't have collisions in IDs when generating IDs among multiple machines in a cluster.  Multithreading support just ensures you don't crash if accessed by multiple threads, it does nothing to prevent collisions with a very high volume of IDs that are being generated from multiple machines.

As a point:  If your stance is indeed this,

> my aim was and is to create a port of dylang's library.

Then your goals, guarantees, protections, and contract (e.g. shortid.Generate(), with the same arguments) should match those provided by dylang's shortid.  Unfortunately, so far I'm not seeing this.

**Comment by dougrday** [comment]
A point to note - in most cases dylang's shortid will usually generate 7-10 character IDs while guaranteeing uniqueness up to a pretty astronomical amount (millions of IDs generated in a single second).

Here's some more information about what composes the ID for dylang's shortid, and how unique it is.
https://github.com/dylang/shortid/issues/58
