### ISSUE TITLE
Emits only "aaaaaa" after some time due to wrong use of Math.Random

### ISSUE THREAD

**Issue by aloker** [bolorundurowb/shortid#6]
I've used your code in a multithreaded server environment, but after some time only "aaaaaaa" is emitted. This is probably due to the fact that you're using the same Math.Random instance across multiple threads. You shouldn't do that: https://msdn.microsoft.com/en-us/library/system.random%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396#ThreadSafety

Especially (bold by me): 

> Instead of instantiating individual Random objects, we recommend that you create a single Random instance to generate all the random numbers needed by your app. However, Random objects are not thread safe. If your app calls Random methods from multiple threads, you must use a synchronization object to ensure that only one thread can access the random number generator at a time. **If you don't ensure that the Random object is accessed in a thread-safe way, calls to methods that return random numbers return 0**.

**Comment by bolorundurowb** [comment]
@aloker the thread unsafeness was raised and I implemented some changes to add thread safety using locks

**Comment by bolorundurowb** [comment]
@aloker if the issue persists after upgrading to version 2.0.0 or above, please feel free to reopen this issue

**Comment by rrmayer** [comment]
I'm actually seeing this with version 2.0.0.  The situation is happening when I'm running multiple unit tests in parallel, which use ShortId in conjunction with AutoFaker to generate mock objects. Once it happens, every id generated is "aaaaaaa".  Oddly, I do have my autofaker item wrapped with a Lock statement, because I suspect it has a similar issue.

I fixed my issue by declaring a static class that uses a lock object, then replacing all references to point to my static generator.

**Comment by taspeotis** [comment]
> I implemented some changes to add thread safety using locks

Literally the first use of `_random` in the source code is done without synchronisation?

https://github.com/bolorundurowb/shortid/blob/master/shortid/ShortId.cs#L27

The second usage is too, reading the instance is synchronised but actually using the instance is not.

```
            lock (threadLock)
            {
                __pool = _pool;
                rand = _random;
            }

// ...

            for (int i = 0; i < length; i++)
            {
                int charIndex = rand.Next(0, pool.Length);
                output[i] =  pool[charIndex];
            }
```

**Comment by bolorundurowb** [comment]
Hey @aloker and @rrmayer I was able to replicate this issue with the code below

```csharp
        private static ConcurrentBag<string> _bag = new ConcurrentBag<string>();
        
        public static void Main(string[] args)
        {
            var stopWatch = new Stopwatch();
            stopWatch.Start();
            var threadList = new List<Thread>();

           for (var i = 0; i < 100; i++)
           {
               var thread = new Thread(GenerateAThousand);
               threadList.Add(thread);
               thread.Start();
           }

           foreach (var thread in threadList)
           {
               thread.Join();
           }
           
           stopWatch.Stop();
           var elapsedTime = stopWatch.ElapsedMilliseconds;
        }
```

**Comment by bolorundurowb** [comment]
Working on a fix

**Comment by bolorundurowb** [comment]
@rrmayer @aloker @taspeotis I have a fix PR opn https://github.com/bolorundurowb/shortid/pull/19. Take a look if you get a chance
